apiVersion: v1
kind: Service

metadata:
  name: apache-service
  namespace: apache

spec:
  ports:
    - name: apache
      port: 80
      targetPort: 80

  selector:
    app: apache

  type: ClusterIP